### ISSUE TITLE
Incompatibility with immersive_portals

### ISSUE THREAD

**Issue by hypixelsbgamer** [Agent59/SpeechToSpell#3]
It keeps giving me error code 1 when I use the mod. Is there any incompatibilities that I don't know of?
When i remove the minecraft actually starts

**Comment by Agent59** [comment]
Would you please paste in the whole error message

**Comment by pawlrip** [comment]
would you please paste in the whole error message or crash-report, which can be found in .minecraft -> crash-reports (sorry for closing the issue, did it by accident)

**Comment by hypixelsbgamer** [comment]
Ok, I'll do that when I get home shouldn't take long

**Comment by hypixelsbgamer** [comment]
I can't get anything else, due to the fact the game doesnt even load it just immediatly gives me a crash

**Comment by hypixelsbgamer** [comment]
its just exit code 1
and it usually has to do with incompatible mods

**Comment by pawlrip** [comment]
please go to .minecraft/crash-reports and paste in the crash-report, also I think you can click a button to show more details when getting exit code 1

**Comment by hypixelsbgamer** [comment]
It's empty. I'll have to get the logs instead

**Comment by hypixelsbgamer** [comment]
[latest.log](https://github.com/Agent59/SpeechToSpell/files/9086299/latest.log)

**Comment by pawlrip** [comment]
It seems like the mod is incompatible with immersive_portals. I'll see what I can do to fix this error

**Comment by hypixelsbgamer** [comment]
Ok. Thanks!
When you do fix it I can't wait to try it out

**Comment by pawlrip** [comment]
I'll close this when its fixed, please leave it open while the issue is still arising

**Comment by hypixelsbgamer** [comment]
Oh ok

**Comment by pawlrip** [comment]
Should be fixed.
I uploaded the new versions to modrinth but I'm having some trouble with curseforge right now, so it might take a little until the new versions can be downloaded from there.
The version numbers haven't changed though, just if you're were wondering why they look the same.

**Comment by pawlrip** [comment]
All uploaded files are up to date
