### ISSUE TITLE
Compatibility with arcanus

### ISSUE THREAD

**Issue by Feliks-WR** [Agent59/SpeechToSpell#4]
PLease make it compatible with arcanus
(use arcanus' wand!??)

**Comment by pawlrip** [comment]
Would you please specify which features you would like to have implemented?

**Comment by pawlrip** [comment]
Due to inactivity on this issue and the mod seeming to [only support Quilt in its newest versions](https://modrinth.com/mod/arcanus/versions) I will close this issue.
