### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by NextRaven10** [Agent59/SpeechToSpell#6]
Is is possible to update this mod to 1.20.1 and are you willing to do it? I would love it :D

Thx for this masterpiece

**Comment by pawlrip** [comment]
It most certainly is possible and I am more than willing to do it. Though because I'm quite busy at the moment, it might take a few weeks.

**Comment by pawlrip** [comment]
The new version is now available on [modrinth](https://modrinth.com/mod/speech_to_spell/version/v0.2.1-1.20.1).
